/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author phibonachos
 */
public class LogFrame extends javax.swing.JFrame {

    /**
     * Creates new form LogFrame
     */
    public LogFrame() {
        initComponents();
    }

    public void printServerLog(String s){
        ServerArea.append(s+"\n");
        ServerArea.setCaretPosition(ServerArea.getDocument().getLength());
    }

    public void printClientLog(String s){
        ClientArea.append(s+"\n");
        ClientArea.setCaretPosition(ClientArea.getDocument().getLength());
    }

    public void printDebugLog(String s){
        DebugArea.append(s+"\n");
        DebugArea.setCaretPosition(DebugArea.getDocument().getLength());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        TabPanel = new javax.swing.JTabbedPane();
        ServerPanel = new javax.swing.JPanel();
        ServerScrollPanel = new javax.swing.JScrollPane();
        ServerArea = new javax.swing.JTextArea();
        ClientPanel = new javax.swing.JPanel();
        ClientScrollPanel = new javax.swing.JScrollPane();
        ClientArea = new javax.swing.JTextArea();
        DebugPanel = new javax.swing.JPanel();
        DebugScrollPanel = new javax.swing.JScrollPane();
        DebugArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ServerScrollPanel.setBorder(null);

        ServerArea.setBackground(new java.awt.Color(0, 0, 0));
        ServerArea.setColumns(20);
        ServerArea.setForeground(new java.awt.Color(51, 255, 51));
        ServerArea.setRows(5);
        ServerScrollPanel.setViewportView(ServerArea);

        javax.swing.GroupLayout ServerPanelLayout = new javax.swing.GroupLayout(ServerPanel);
        ServerPanel.setLayout(ServerPanelLayout);
        ServerPanelLayout.setHorizontalGroup(
                ServerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ServerScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        ServerPanelLayout.setVerticalGroup(
                ServerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ServerScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        TabPanel.addTab("Server Log", ServerPanel);

        ClientScrollPanel.setBorder(null);

        ClientArea.setBackground(new java.awt.Color(0, 0, 0));
        ClientArea.setColumns(20);
        ClientArea.setForeground(new java.awt.Color(51, 255, 51));
        ClientArea.setRows(5);
        ClientScrollPanel.setViewportView(ClientArea);

        javax.swing.GroupLayout ClientPanelLayout = new javax.swing.GroupLayout(ClientPanel);
        ClientPanel.setLayout(ClientPanelLayout);
        ClientPanelLayout.setHorizontalGroup(
                ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ClientScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        ClientPanelLayout.setVerticalGroup(
                ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ClientScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        TabPanel.addTab("Client Log", ClientPanel);

        DebugScrollPanel.setBorder(null);

        DebugArea.setBackground(new java.awt.Color(0, 0, 0));
        DebugArea.setColumns(20);
        DebugArea.setForeground(new java.awt.Color(51, 255, 51));
        DebugArea.setRows(5);
        DebugScrollPanel.setViewportView(DebugArea);

        javax.swing.GroupLayout DebugPanelLayout = new javax.swing.GroupLayout(DebugPanel);
        DebugPanel.setLayout(DebugPanelLayout);
        DebugPanelLayout.setHorizontalGroup(
                DebugPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DebugScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        DebugPanelLayout.setVerticalGroup(
                DebugPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DebugScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        TabPanel.addTab("Notification Log", DebugPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TabPanel)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TabPanel)
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextArea ClientArea;
    private javax.swing.JPanel ClientPanel;
    private javax.swing.JScrollPane ClientScrollPanel;
    private javax.swing.JTextArea DebugArea;
    private javax.swing.JPanel DebugPanel;
    private javax.swing.JScrollPane DebugScrollPanel;
    private javax.swing.JTextArea ServerArea;
    private javax.swing.JPanel ServerPanel;
    private javax.swing.JScrollPane ServerScrollPanel;
    private javax.swing.JTabbedPane TabPanel;
    // End of variables declaration
}
