package parser;

public enum TokenType {
    EOF, MESSAGELIT, IP, IDENT, NEWLINE, SKIP, MESSAGE, USER, TOPIC,
    LIST, ADD, REMOVE, CONNECT, DISCONNECT, SUBSCRIBE, UNSUBSCRIBE, HELP, IN, AS, EXIT, START
}
